name: Test package
on: 
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: 
         - ubuntu-latest
         - ubuntu-18.04
         - macos-latest
         - macos-11
         - windows-latest
         - windows-2016
         - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install packages
        run: |
          npm install
      - name: get dir path
        id: get-path
        uses: michmich112/get-actions-dir-path@main
      - name: Test package
        run: |
          npm run test
        env:
          DIRPATH: ${{ steps.get-path.outputs.dir-path }}

